name: flutter_template
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ui tools
  cupertino_icons: ^1.0.6
  reactive_forms: ^16.1.1
  shimmer: ^2.0.0
  waterfall_flow: ^3.0.2

  # localizations
  intl: any

  # api_client
  dio: ^5.4.3+1
  retrofit: ^4.1.0

  # injections
  injectable: ^2.4.1
  get_it: ^7.7.0

  # state management
  flutter_bloc: ^8.1.5
  provider: ^6.1.2

  # routing
  auto_route: ^8.1.1

  # annotations
  json_annotation: ^4.8.1

  # utils
  email_validator: ^2.1.17
  equatable: ^2.0.5

  # storages
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  import_sorter: ^4.6.0
  injectable_generator: ^2.6.1
  flutter_gen_runner: ^5.4.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/presentation/utils/assets
  fonts:
    enabled: false

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
